Add kubernetes vault auth
hairyhenderson/go-fsimpl pull request #161
Opened 2022-09-20 16:22 UTC by Joibel

This addresses #152. Please do ask for changes if you don't like it, although I'm busy the beginning of this week.

This uses a jwt token usually mounted at a well known location to authenticate as a 'role' in vault which must be provided via the environment.

See https://www.vaultproject.io/docs/auth/kubernetes

2022-09-20 17:01 UTC, hairyhenderson commented on vaultfs/auth.go
> +		return fmt.Errorf("kubernetes auth failure: no jwt found at %s", jwtPath)
If no JWT was found, wouldn't the `err` be an `fs.ErrNotExist` or so?

Or is this the case where the file exists but is empty? If so, I think it's worth being more explicit about that, perhaps something like:

```suggestion
	if len(jwt) == 0 {
		return fmt.Errorf("kubernetes auth failure: file %q is empty", jwtPath)
```

2022-09-20 17:13 UTC, hairyhenderson commented
Thanks for this @Joibel! Overall it looks good. I have a bit of a naming nitpick though - you've used term "JWT" throughout, which is accurate, but I wonder if replacing that with "token" would be clearer.

The Vault docs and the Kubernetes docs both mention "Service Account Token" and "Token" more than "JWT", and the token file itself is named `token`, so I think that would be a bit more intuitive.

Have you tested this locally in a real k8s cluster?

2022-09-20 22:13 UTC, Joibel commented
I've renamed JWT to saToken. Token by itself is too confusable with the VAULT_TOKEN you get back from vault once logged in and used everywhere else, and VAULT_AUTH_SERVICE_ACCOUNT_TOKEN_PATH got a bit long for my liking.

I have tested this using a real k8s cluster against a real vault, so it's all good there.

2022-09-21 15:32 UTC, hairyhenderson commented
> I've renamed JWT to saToken

great, that works!

2022-09-21 15:33 UTC, hairyhenderson commented on vaultfs/auth.go
> +// role is omitted, the value will be read from the $VAULT_AUTH_ROLE. If jwtPath is
```suggestion
// role is omitted, the value will be read from the $VAULT_AUTH_ROLE. If saTokenPath is
```

2022-09-21 15:54 UTC, hairyhenderson commented on vaultfs/auth.go
> +// omitted we will attempt to read from $VAULT_AUTH_SATOKEN_PATH environment variable or
Actually I wonder if `VAULT_AUTH_KUBERNETES_TOKEN_PATH` would be clearer:

```suggestion
// omitted we will attempt to read from $VAULT_AUTH_KUBERNETES_TOKEN_PATH environment variable or
```

This follows somewhat the same naming scheme as other variables - e.g. `VAULT_AUTH_GITHUB_TOKEN`...

2022-09-21 15:59 UTC, hairyhenderson commented on vaultfs/auth.go
> +		map[string]interface{}{"role": role, "saToken": string(saToken)})
the key shouldn't have changed:

```suggestion
		map[string]interface{}{"role": role, "jwt": string(saToken)})
```

2022-09-24 17:31 UTC, hairyhenderson requested changes
Thanks again for working on this @Joibel!

I think I'd rather use the Vault API's Kubernetes auth method instead - see https://pkg.go.dev/github.com/hashicorp/vault/api/auth/kubernetes, and #162/#171 for further details.

2022-09-25 13:39 UTC, hairyhenderson commented
Superseded by #171 - @Joibel Let me know if there's anything that doesn't work with the Vault API's [`kubernetes`](https://pkg.go.dev/github.com/hashicorp/vault/api/auth/kubernetes) auth method, and we could enhance that.

For now though I'm going to close this PR - again, thank you for taking the time to work on this!

2022-09-25 13:39 UTC, closed without merging